//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinderCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Likes
    {
        public int LikesID { get; set; }
        public Nullable<int> FrstUser { get; set; }
        public Nullable<int> SecUser { get; set; }
    }
}
