//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinderCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Info
    {
        public int ID_User_Info { get; set; }
        public string Education { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<int> Weight { get; set; }
        public string About { get; set; }
        public Nullable<int> Zodiac_ID { get; set; }
        public string Photo { get; set; }
        public string Photo_format { get; set; }
    }
}
